In [139]:
import numpy as np

n = 3
m = 2
G = np.array([[1, 0, 1], [1, 1, 0]], dtype=int)

word = np.array([1,0,0,0,0,0,0,0,0,0], dtype=int)

In [140]:
def hamming_weight(word):
    return word.sum()

def hamming_dist(u, v):
    k = (u+v) % 2
    return hamming_weight(k)

def _compute_transition(bit, M):
    M = np.concatenate([[bit], M])
    v = np.logical_and(G, M)
    v = v.sum(axis=1) % 2
    M = M[:-1]
    return v, M

In [141]:
def encode(word):
    M = np.zeros(m)
    V = []
    for bit in word:
        v, M = _compute_transition(bit, M)
        V.append(v)
    V = np.array(V).reshape(-1)
    return V

word = encode(word)

In [142]:
word

array([1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [167]:
from cmath import inf

word = word.reshape((-1, m))
print(word)
minDist = {}
minPath = {}

for i in range(2**m):
    minDist[i] = inf
    # minPath[i] = [i]
    minPath[i] = []
minDist[0] = 0

for k in range(word.shape[0]):
    bits = np.array(list(range(2**m)), dtype='uint8')
    nodes = np.unpackbits(bits).reshape((-1, 8))[:, -m:]
    newDist = {}
    newPath = {}
    for node_repr, node in enumerate(nodes):
        # print(node)

        v1, child1 = _compute_transition(0, node)
        v2, child2 = _compute_transition(1, node)

        # print(f'v1={v1} child1={child1} node_repr={node_repr}')
        # print(f'v2={v2} child1={child2} node_repr={node_repr}')

        repr1 = np.packbits(np.flip(child1), bitorder='little')[0]
        # print(f'    repr1={repr1}')
        nd = minDist[node_repr] + hamming_dist(v1, np.array(word[k]))
        # print(f' nd child1: {nd}')
        if (newDist.get(repr1) and nd < newDist.get(repr1)) or newDist.get(repr1) is None:
            # print(f'atualizando newDist[{repr1}] = {nd}')
            newDist[repr1] = nd
            newPath[repr1] = minPath[node_repr] + [0]

        repr2 = np.packbits(np.flip(child2), bitorder='little')[0]
        # print(f'    repr2={repr2}')
        nd = minDist[node_repr] + hamming_dist(v2, np.array(word[k]))
        # print(f' nd child2: {nd}')
        # print(f'  newDist {not newDist.get(repr2)}')
        if (newDist.get(repr2) and nd < newDist.get(repr2)) or newDist.get(repr2) is None:
            # print(f'cond1: {(newDist.get(repr2) and nd < newDist.get(repr2))}  cond2: {(not newDist.get(repr2))}')
            # print(f'atualizando newDist[{repr2}] = {nd}')
            newDist[repr2] = nd
            newPath[repr2] = minPath[node_repr] + [1]

    
    minDist = newDist
    minPath = newPath

    for k in minDist.keys():
        print(f' k={k}   minDist={minDist[k]}  minPath={minPath[k]}')

    print('&&&&&&&&&')

node = min(minDist, key=minDist.get)
path = minPath[node]
np.array(path)


[[1 1]
 [0 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
 k=0   minDist=2  minPath=[0]
 k=2   minDist=0  minPath=[1]
 k=1   minDist=inf  minPath=[0]
 k=3   minDist=inf  minPath=[1]
&&&&&&&&&
 k=0   minDist=3  minPath=[0, 0]
 k=2   minDist=3  minPath=[0, 1]
 k=1   minDist=0  minPath=[1, 0]
 k=3   minDist=2  minPath=[1, 1]
&&&&&&&&&
 k=0   minDist=0  minPath=[1, 0, 0]
 k=2   minDist=2  minPath=[1, 0, 1]
 k=1   minDist=3  minPath=[1, 1, 0]
 k=3   minDist=3  minPath=[0, 1, 1]
&&&&&&&&&
 k=0   minDist=0  minPath=[1, 0, 0, 0]
 k=2   minDist=2  minPath=[1, 0, 0, 1]
 k=1   minDist=3  minPath=[1, 0, 1, 0]
 k=3   minDist=3  minPath=[1, 0, 1, 1]
&&&&&&&&&
 k=0   minDist=0  minPath=[1, 0, 0, 0, 0]
 k=2   minDist=2  minPath=[1, 0, 0, 0, 1]
 k=1   minDist=3  minPath=[1, 0, 0, 1, 0]
 k=3   minDist=3  minPath=[1, 0, 0, 1, 1]
&&&&&&&&&
 k=0   minDist=0  minPath=[1, 0, 0, 0, 0, 0]
 k=2   minDist=2  minPath=[1, 0, 0, 0, 0, 1]
 k=1   minDist=3  minPath=[1, 0, 0, 0, 1, 0]
 k=3   minDist=3  mi

In [168]:
path

[1, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [83]:
bits = np.array(list(range(2**m)), dtype='uint8')
nodes = np.unpackbits(bits)

In [78]:
bits

array([0, 1, 2, 3, 4, 5, 6, 7], dtype=uint8)

In [94]:
d = {
}

In [111]:
np.flip(np.array([1,2,3]))

array([3, 2, 1])

In [97]:
d[0]

KeyError: 0

In [149]:
d = {}

In [156]:
if d.get(2):
    print('hello')

In [153]:
del d[2]

In [162]:
inf > 3

True